In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

In [2]:
ROOT = Path.cwd().parent

DATASETS = ROOT / "datasets"

EEDI_INTERACTIONS = DATASETS / "eedi_interactions"
EEDI_MISCONCEPTIONS = DATASETS / "eedi_misconceptions"

print("Project root:", ROOT)
print("Datasets:", DATASETS)

Project root: c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet
Datasets: c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets

In [3]:
print("EEDI Interactions:")
for item in EEDI_INTERACTIONS.iterdir():
    print(" -", item.name)

print("\nEEDI Misconceptions:")
for item in EEDI_MISCONCEPTIONS.iterdir():
    print(" -", item.name)

EEDI Interactions:
 - .DS_Store
 - images
 - metadata
 - test_data
 - train_data

EEDI Misconceptions:
 - misconception_mapping.csv
 - sample_submission.csv
 - test.csv
 - train.csv

In [4]:
print("TRAIN DATA")
for file in (EEDI_INTERACTIONS / "train_data").rglob("*"):
    if file.is_file():
        print(f"{file.name:<40} {file.stat().st_size / 1024**2:.2f} MB")

print("\nTEST DATA")
for file in (EEDI_INTERACTIONS / "test_data").rglob("*"):
    if file.is_file():
        print(f"{file.name:<40} {file.stat().st_size / 1024**2:.2f} MB")

TRAIN DATA
.DS_Store                                0.01 MB
train_task_1_2.csv                       410.13 MB
train_task_3_4.csv                       30.26 MB

TEST DATA
quality_response_remapped_private.csv    0.00 MB
quality_response_remapped_public.csv     0.00 MB
test_private_answers_task_1.csv          43.70 MB
test_private_answers_task_2.csv          43.70 MB
test_private_task_4.csv                  1.22 MB
test_private_task_4_more_splits.csv      2.10 MB
test_public_answers_task_1.csv           43.70 MB
test_public_answers_task_2.csv           43.70 MB
test_public_task_4_more_splits.csv       3.07 MB

In [5]:
metadata_path = EEDI_INTERACTIONS / "metadata"

print("METADATA FILES\n")

for file in metadata_path.glob("*.csv"):
    df = pd.read_csv(file)

    print(f"{file.name}")
    print(f"  Rows: {len(df):,}")
    print(f"  Columns: {len(df.columns)}")
    print(f"  Columns: {list(df.columns)}")
    print()

METADATA FILES

answer_metadata_task_1_2.csv
  Rows: 19,834,820
  Columns: 6
  Columns: ['AnswerId', 'DateAnswered', 'Confidence', 'GroupId', 'QuizId', 'SchemeOfWorkId']

answer_metadata_task_3_4.csv
  Rows: 1,508,917
  Columns: 6
  Columns: ['AnswerId', 'DateAnswered', 'Confidence', 'GroupId', 'QuizId', 'SchemeOfWorkId']

question_metadata_task_1_2.csv
  Rows: 27,613
  Columns: 2
  Columns: ['QuestionId', 'SubjectId']

question_metadata_task_3_4.csv
  Rows: 948
  Columns: 2
  Columns: ['QuestionId', 'SubjectId']

student_metadata_task_1_2.csv
  Rows: 118,971
  Columns: 4
  Columns: ['UserId', 'Gender', 'DateOfBirth', 'PremiumPupil']

student_metadata_task_3_4.csv
  Rows: 6,148
  Columns: 4
  Columns: ['UserId', 'Gender', 'DateOfBirth', 'PremiumPupil']

subject_metadata.csv
  Rows: 388
  Columns: 4
  Columns: ['SubjectId', 'Name', 'ParentId', 'Level']

In [6]:
train_path = EEDI_INTERACTIONS / "train_data"

print("TRAINING FILES\n")

for file in train_path.rglob("*"):
    if file.is_file():
        print(f"{file.name:<45} {file.stat().st_size / 1024**2:.2f} MB")

TRAINING FILES

.DS_Store                                     0.01 MB
train_task_1_2.csv                            410.13 MB
train_task_3_4.csv                            30.26 MB

In [7]:
test_path = EEDI_INTERACTIONS / "test_data"

print("TEST FILES\n")

for file in test_path.rglob("*"):
    if file.is_file():
        print(f"{file.name:<45} {file.stat().st_size / 1024**2:.2f} MB")

TEST FILES

quality_response_remapped_private.csv         0.00 MB
quality_response_remapped_public.csv          0.00 MB
test_private_answers_task_1.csv               43.70 MB
test_private_answers_task_2.csv               43.70 MB
test_private_task_4.csv                       1.22 MB
test_private_task_4_more_splits.csv           2.10 MB
test_public_answers_task_1.csv                43.70 MB
test_public_answers_task_2.csv                43.70 MB
test_public_task_4_more_splits.csv            3.07 MB

In [8]:
subjects = pd.read_csv(
    metadata_path / "subject_metadata.csv"
)

print(subjects.head(10))
print("\nLevels:")
print(subjects["Level"].value_counts().sort_index())

print("\nMissing values:")
print(subjects.isnull().sum())

   SubjectId                                            Name  ParentId  Level
0          3                                           Maths       NaN      0
1         32                                          Number       3.0      1
2         33                                          BIDMAS     144.0      3
3         34                          Upper and Lower Bounds     141.0      3
4         35                                  Calculator Use      32.0      2
5         36                                        Decimals      32.0      2
6         37                   Factors, Multiples and Primes      32.0      2
7         38  Fractions, Decimals and Percentage Equivalence      32.0      2
8         39                                       Fractions      32.0      2
9         40                       Indices, Powers and Roots      32.0      2

Levels:
Level
0      2
1      9
2     69
3    308
Name: count, dtype: int64

Missing values:
SubjectId    0
Name         0
ParentId     2
Level        0
dtype: int64

In [9]:
print("Parent subjects:", subjects["ParentId"].isna().sum())
print("Child subjects:", subjects["ParentId"].notna().sum())

print("\nSample hierarchy:")
print(
    subjects[
        ["SubjectId", "Name", "ParentId", "Level"]
    ].sort_values(["Level", "SubjectId"]).head(30).to_string(index=False)
)

Parent subjects: 2
Child subjects: 386

Sample hierarchy:
 SubjectId                                           Name  ParentId  Level
         3                                          Maths       NaN      0
      1642                                        Science       NaN      0
        32                                         Number       3.0      1
        49                                        Algebra       3.0      1
        71                           Geometry and Measure       3.0      1
       101                            Data and Statistics       3.0      1
       119                                  Advanced Pure       3.0      1
       149                             Advanced Mechanics       3.0      1
       151                            Advanced Statistics       3.0      1
       692                                        Physics    1642.0      1
      1156                                   Maths-Others       3.0      1
        35                                 Calculator Use      32.0      2
        36                                       Decimals      32.0      2
        37                  Factors, Multiples and Primes      32.0      2
        38 Fractions, Decimals and Percentage Equivalence      32.0      2
        39                                      Fractions      32.0      2
        40                      Indices, Powers and Roots      32.0      2
        42                               Negative Numbers      32.0      2
        44                                    Percentages      32.0      2
        45                                     Proportion      32.0      2
        46                                          Ratio      32.0      2
        48                                          Surds      32.0      2
        54                           Straight Line Graphs      49.0      2
        55                               Quadratic Graphs      49.0      2
        59                                   Inequalities      49.0      2
        61                                      Sequences      49.0      2
        62            Writing and Simplifying Expressions      49.0      2
        68                    Transformation of Functions      49.0      2
        74                                         Angles      71.0      2
        77                                        Circles      71.0      2

In [10]:
miscon_path = EEDI_MISCONCEPTIONS

train_mis = pd.read_csv(miscon_path / "train.csv")
mapping = pd.read_csv(miscon_path / "misconception_mapping.csv")

print("MISCONCEPTION TRAIN")
print("Shape:", train_mis.shape)
print("\nColumns:")
print(train_mis.columns.tolist())

print("\nFirst 3 rows:")
display(train_mis.head(3))

print("\nMISCONCEPTION MAPPING")
print("Shape:", mapping.shape)
print(mapping.head(5))

MISCONCEPTION TRAIN
Shape: (1869, 15)

Columns:
['QuestionId', 'ConstructId', 'ConstructName', 'SubjectId', 'SubjectName', 'CorrectAnswer', 'QuestionText', 'AnswerAText', 'AnswerBText', 'AnswerCText', 'AnswerDText', 'MisconceptionAId', 'MisconceptionBId', 'MisconceptionCId', 'MisconceptionDId']

First 3 rows:

,QuestionId,ConstructId,ConstructName,SubjectId,SubjectName,CorrectAnswer,QuestionText,AnswerAText,AnswerBText,AnswerCText,AnswerDText,MisconceptionAId,MisconceptionBId,MisconceptionCId,MisconceptionDId
0,0,856,Use the order of operations to carry out calculations involving powers,33,BIDMAS,A,\[\n3 \times 2+4-5\n\]\nWhere do the brackets need to go to make the answer equal \( 13 \) ?,\( 3 \times(2+4)-5 \),\( 3 \times 2+(4-5) \),\( 3 \times(2+4-5) \),Does not need brackets,NaN,NaN,NaN,1672.0
1,1,1612,Simplify an algebraic fraction by factorising the numerator,1077,Simplifying Algebraic Fractions,D,"Simplify the following, if possible: \( \frac{m^{2}+2 m-3}{m-3} \)",\( m+1 \),\( m+2 \),\( m-1 \),Does not simplify,2142.0,143.0,2142.0,NaN
2,2,2774,Calculate the range from a list of data,339,Range and Interquartile Range from a List of Data,B,"Tom and Katie are discussing the \( 5 \) plants with these heights:\n\( 24 \mathrm{~cm}, 17 \mat...",Only\nTom,Only\nKatie,Both Tom and Katie,Neither is correct,1287.0,NaN,1287.0,1073.0

MISCONCEPTION MAPPING
Shape: (2587, 2)
   MisconceptionId  \
0                0
1                1
2                2
3                3
4                4

                                                                MisconceptionName
0                      Does not know that angles in a triangle sum to 180 degrees
1                        Uses dividing fractions method for multiplying fractions
2                                   Believes there are 100 degrees in a full turn
3           Thinks a quadratic without a non variable term, can not be factorised
4  Believes addition of terms and powers of terms are equivalent e.g. a + c = a^c

In [11]:
train_file = train_path / "train_task_1_2.csv"

header = pd.read_csv(train_file, nrows=5)

print("Shape of sample:", header.shape)
print("\nColumns:")
print(header.columns.tolist())

display(header.head())

Shape of sample: (5, 6)

Columns:
['QuestionId', 'UserId', 'AnswerId', 'IsCorrect', 'CorrectAnswer', 'AnswerValue']

   QuestionId  UserId  AnswerId  IsCorrect  CorrectAnswer  AnswerValue
0       16997   65967  12453206          0              4            2
1       16531   62121  15686710          1              1            1
2       15911   50013  13598796          0              3            1
3        1701  104909  10511925          0              4            3
4       22896   21748    941747          0              1            4

In [12]:
print(header.dtypes)

QuestionId       int64
UserId           int64
AnswerId         int64
IsCorrect        int64
CorrectAnswer    int64
AnswerValue      int64
dtype: object

In [13]:
sample = pd.read_csv(train_file, nrows=20)

display(sample)

    QuestionId  UserId  AnswerId  IsCorrect  CorrectAnswer  AnswerValue
0        16997   65967  12453206          0              4            2
1        16531   62121  15686710          1              1            1
2        15911   50013  13598796          0              3            1
3         1701  104909  10511925          0              4            3
4        22896   21748    941747          0              1            4
5        20968   67570    626158          1              4            4
6         8826    5257   6163686          1              1            1
7         9331   82336   7433440          1              2            2
8        12574   11665  18336567          1              2            2
9         1383  104459  17496424          0              3            1
10       21568   87935  17488010          1              4            4
11       15962   77530  11435172          0              2            3
12        9952    5685  19507712          1              3            3
13       25200   97689   3706446          0              2            4
14       20640   99529  12214186          0              3            4
15       15929  106953   2997559          1              2            2
16       12597   56677  17045948          1              1            1
17       19521   31088  13670348          1              4            4
18        2711   51027  10055988          1              3            3
19       14158   27438  11912574          1              4            4

In [14]:
print("Unique AnswerIds:", sample["AnswerId"].nunique())

if "UserId" in sample.columns:
    print("Unique UserIds:", sample["UserId"].nunique())

if "QuestionId" in sample.columns:
    print("Unique QuestionIds:", sample["QuestionId"].nunique())

print("\nColumns containing 'Id':")
print([c for c in sample.columns if "Id" in c])

Unique AnswerIds: 20
Unique UserIds: 20
Unique QuestionIds: 20

Columns containing 'Id':
['QuestionId', 'UserId', 'AnswerId']

In [15]:
miscon_cols = [
    "MisconceptionAId",
    "MisconceptionBId",
    "MisconceptionCId",
    "MisconceptionDId"
]

print("Misconception labels per option:\n")

for col in miscon_cols:
    count = train_mis[col].notna().sum()
    print(f"{col}: {count:,} labeled")

print("\nTotal labeled distractors:",
      train_mis[miscon_cols].notna().sum().sum())

print("\nUnique misconception IDs:",
      pd.unique(train_mis[miscon_cols].values.ravel()).shape[0] - 1)

Misconception labels per option:

MisconceptionAId: 1,135 labeled
MisconceptionBId: 1,118 labeled
MisconceptionCId: 1,080 labeled
MisconceptionDId: 1,037 labeled

Total labeled distractors: 4370

Unique misconception IDs: 1604

In [16]:
print("Columns:")
print(mapping.columns.tolist())

print("\nShape:", mapping.shape)

display(mapping.head(10))

print("\nMissing values:")
print(mapping.isnull().sum())

Columns:
['MisconceptionId', 'MisconceptionName']

Shape: (2587, 2)

,MisconceptionId,MisconceptionName
0,0,Does not know that angles in a triangle sum to 180 degrees
1,1,Uses dividing fractions method for multiplying fractions
2,2,Believes there are 100 degrees in a full turn
3,3,"Thinks a quadratic without a non variable term, can not be factorised"
4,4,Believes addition of terms and powers of terms are equivalent e.g. a + c = a^c
5,5,"When measuring a reflex angle, gives the acute or obtuse angle that sums to 360 instead"
6,6,Can identify the multiplier used to form an equivalent fraction but does not apply to the numerator
7,7,Believes gradient = change in y
8,8,Student thinks that any two angles along a straight line are equal
9,9,Thinks there are 180 degrees in a full turn

Missing values:
MisconceptionId      0
MisconceptionName    0
dtype: int64

In [17]:
misconception_ids = pd.unique(
    train_mis[miscon_cols].values.ravel()
)

misconception_ids = misconception_ids[
    pd.notna(misconception_ids)
].astype(int)

print("Unique misconception IDs:", len(np.unique(misconception_ids)))
print("Minimum ID:", misconception_ids.min())
print("Maximum ID:", misconception_ids.max())

print("\nMost frequent misconceptions:")
print(
    pd.Series(misconception_ids)
    .value_counts()
    .head(15)
)

Unique misconception IDs: 1604
Minimum ID: 0
Maximum ID: 2586

Most frequent misconceptions:
1672    1
2142    1
143     1
1287    1
1073    1
1180    1
1818    1
686     1
329     1
847     1
2123    1
2273    1
2133    1
907     1
1514    1
Name: count, dtype: int64

In [18]:
question_meta_12 = pd.read_csv(
    metadata_path / "question_metadata_task_1_2.csv"
)

print("Dataset 1 QuestionId range:")
print(
    question_meta_12["QuestionId"].min(),
    "→",
    question_meta_12["QuestionId"].max()
)

print("\nDataset 2 QuestionId range:")
print(
    train_mis["QuestionId"].min(),
    "→",
    train_mis["QuestionId"].max()
)

print("\nDataset 1 unique QuestionIds:",
      question_meta_12["QuestionId"].nunique())

print("Dataset 2 unique QuestionIds:",
      train_mis["QuestionId"].nunique())

Dataset 1 QuestionId range:
0 → 27612

Dataset 2 QuestionId range:
0 → 1868

Dataset 1 unique QuestionIds: 27613
Dataset 2 unique QuestionIds: 1869

In [19]:
ids_1 = set(question_meta_12["QuestionId"])
ids_2 = set(train_mis["QuestionId"])

overlap = ids_1 & ids_2

print("Question IDs in Dataset 1:", len(ids_1))
print("Question IDs in Dataset 2:", len(ids_2))
print("Directly overlapping IDs:", len(overlap))

print("\nPercentage of Dataset 2 IDs overlapping:",
      f"{len(overlap) / len(ids_2) * 100:.2f}%")

print("\nFirst 20 overlapping IDs:")
print(sorted(overlap)[:20])

Question IDs in Dataset 1: 27613
Question IDs in Dataset 2: 1869
Directly overlapping IDs: 1869

Percentage of Dataset 2 IDs overlapping: 100.00%

First 20 overlapping IDs:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [20]:
fraction_mis = train_mis[
    train_mis["SubjectId"] == 39
].copy()

print("Fraction misconception questions:",
      len(fraction_mis))

print("\nUnique constructs:",
      fraction_mis["ConstructId"].nunique())

print("\nConstructs:")
display(
    fraction_mis[
        ["ConstructId", "ConstructName"]
    ].drop_duplicates()
    .sort_values("ConstructId")
)

Fraction misconception questions: 0

Unique constructs: 0

Constructs:

Empty DataFrame
Columns: [ConstructId, ConstructName]
Index: []

In [21]:
subject_dist = (
    train_mis.groupby(["SubjectId", "SubjectName"])
    .size()
    .sort_values(ascending=False)
)

print("Unique subjects:", train_mis["SubjectId"].nunique())

display(subject_dist.head(30))

Unique subjects: 163

SubjectId  SubjectName
64         Linear Equations                                                    53
171        Linear Sequences (nth term)                                         44
33         BIDMAS                                                              37
75         Area of Simple Shapes                                               36
65         Quadratic Equations                                                 36
202        Place Value                                                         31
70         Writing Expressions                                                 31
649        Function Machines                                                   30
224        Multiplying and Dividing with Decimals                              30
67         Substitution into Formula                                           30
92         Reflection                                                          28
230        Adding and Subtracting Fractions                                    28
209        Time                                                                28
204        Mental Multiplication and Division                                  28
181        Basic Angle Facts (straight line, opposite, around a point, etc)    27
102        Averages (mean, median, mode) from a List of Data                   26
58         Real Life Graphs                                                    25
203        Mental Addition and Subtraction                                     25
233        Percentages of an Amount                                            24
245        Squares, Cubes, etc                                                 24
51         Expanding Double Brackets                                           23
63         Simultaneous Equations                                              22
53         Factorising into a Double Bracket                                   22
197        Volume and Capacity Units                                           22
211        Adding and Subtracting Negative Numbers                             21
334        Writing Ratios                                                      21
214        Rounding to Decimal Places                                          20
213        Rounding to the Nearest Whole (10, 100, etc)                        20
50         Expanding Single Brackets                                           19
219        Factors and Highest Common Factor                                   18
dtype: int64

In [22]:
fraction_subjects = train_mis[
    train_mis["SubjectName"].str.contains(
        "fraction", case=False, na=False
    )
][["SubjectId", "SubjectName"]].drop_duplicates()

print("Fraction-related subjects:")
display(fraction_subjects.sort_values("SubjectId"))

Fraction-related subjects:

     SubjectId                                     SubjectName
47         225                          Fractions of an Amount
338        226                            Equivalent Fractions
37         227                           Simplifying Fractions
61         228                              Ordering Fractions
60         229  Converting Mixed Number and Improper Fractions
8          230                Adding and Subtracting Fractions
116        231                           Multiplying Fractions
43         232                              Dividing Fractions
135        237       Converting between Fractions and Decimals
6          238    Converting between Fractions and Percentages
1         1077                 Simplifying Algebraic Fractions
19        1078      Adding and Subtracting Algebraic Fractions
166       1079    Multiplying and Dividing Algebraic Fractions
199       1082                 Recurring Decimals to Fractions

In [23]:
fraction_mis = train_mis[
    train_mis["SubjectName"].str.contains(
        "fraction", case=False, na=False
    )
].copy()

print("Fraction-related questions:", len(fraction_mis))
print("Unique constructs:", fraction_mis["ConstructId"].nunique())
print("Unique subjects:", fraction_mis["SubjectId"].nunique())

display(
    fraction_mis[
        ["ConstructId", "ConstructName"]
    ].drop_duplicates()
    .sort_values("ConstructId")
)

Fraction-related questions: 167
Unique constructs: 64
Unique subjects: 14

,ConstructId,ConstructName
199,328,Identify rational and irrational numbers
842,362,Convert fractions less than 1 to terminating decimals of 1 decimal place
1002,363,Convert fractions less than 1 to terminating decimals of 2 decimal places
1412,364,Convert fractions less than 1 to terminating decimals of 3 or more decimal places
148,369,Convert terminating decimals greater than 1 to fractions
...,...,...
1685,3193,Express a division as a fraction
116,3218,Find missing numbers in a fraction multiplication
135,3319,"Solve problems involving converting between fractions, decimals and percentages"
1043,3320,Use inequality notation to order fractions with the same numerators
146,3342,Read fractions

In [24]:
first_questions = question_meta_12[
    question_meta_12["QuestionId"].isin(
        train_mis["QuestionId"]
    )
].copy()

print("Matched QuestionIds:", len(first_questions))

print("\nDataset 1 subjects represented:")
display(
    first_questions["SubjectId"]
    .value_counts()
    .head(20)
)

Matched QuestionIds: 1869

Dataset 1 subjects represented:

SubjectId
[3, 32, 144, 204]    64
[3, 32, 144, 202]    61
[3, 32, 144, 203]    54
[3, 49, 64, 154]     38
[3, 71, 98, 209]     37
[3, 32, 39, 225]     34
[3, 49, 61, 171]     30
[3, 32, 40, 247]     23
[3, 32, 44, 233]     22
[3, 32, 37, 220]     22
[3, 71, 75, 178]     22
[3, 71, 100, 189]    22
[3, 32, 141, 213]    21
[3, 32, 39, 230]     20
[3, 32, 37, 221]     20
[3, 49, 60, 156]     18
[3, 32, 144, 207]    18
[3, 32, 38, 237]     18
[3, 32, 45, 243]     17
[3, 71, 97, 279]     16
Name: count, dtype: int64

In [25]:
comparison = train_mis.merge(
    question_meta_12,
    on="QuestionId",
    how="left",
    suffixes=("_miscon", "_eedi")
)

print("Rows:", len(comparison))
print("Missing EEDI SubjectId:",
      comparison["SubjectId_eedi"].isna().sum())

display(
    comparison[
        [
            "QuestionId",
            "SubjectId_miscon",
            "SubjectName",
            "SubjectId_eedi"
        ]
    ].head(20)
)

Rows: 1869
Missing EEDI SubjectId: 0

,QuestionId,SubjectId_miscon,SubjectName,SubjectId_eedi
0,0,33,BIDMAS,"[3, 71, 75, 178]"
1,1,1077,Simplifying Algebraic Fractions,"[3, 101, 105, 342]"
2,2,339,Range and Interquartile Range from a List of Data,"[3, 49, 55, 268]"
3,3,88,Properties of Quadrilaterals,"[3, 32, 40, 247]"
4,4,67,Substitution into Formula,"[3, 32, 144, 207]"
5,5,75,Area of Simple Shapes,"[3, 32, 39, 225]"
6,6,238,Converting between Fractions and Percentages,"[3, 49, 64, 154]"
7,7,224,Multiplying and Dividing with Decimals,"[3, 49, 64, 154]"
8,8,230,Adding and Subtracting Fractions,"[3, 32, 141, 214]"
9,9,164,Transformations of functions in the form f(x),"[3, 49, 69, 154]"
10,10,335,Expanding Triple Brackets and more,"[3, 71, 100, 189]"
11,11,85,Nets,"[3, 32, 144, 203]"
12,12,182,Angle Facts with Parallel Lines,"[3, 71, 97, 282]"
13,13,209,Time,"[3, 49, 64, 154]"
14,14,69,Trial and Improvement and Iterative Methods,"[3, 101, 102, 338]"
15,15,75,Area of Simple Shapes,"[3, 32, 141, 213]"
16,16,241,Sharing in a Ratio,"[3, 32, 36, 223]"
17,17,210,Ordering Negative Numbers,"[3, 32, 39, 228]"
18,18,211,Adding and Subtracting Negative Numbers,"[3, 71, 95, 278]"
19,19,1078,Adding and Subtracting Algebraic Fractions,"[3, 32, 144, 206]"