In [1]:
import pandas as pd
import numpy as np
import joblib

from pathlib import Path

In [2]:
ROOT = Path.cwd().parent

DATASETS = ROOT / "datasets"
INTERACTIONS = DATASETS / "eedi_interactions"

MODELS = ROOT / "models"
MODELS.mkdir(exist_ok=True)

print("Project root:")
print(ROOT)

print("\nEEDI interactions:")
print(INTERACTIONS)

print("\nModels:")
print(MODELS)

Project root:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet

EEDI interactions:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets\eedi_interactions

Models:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\models

In [3]:
print("EEDI interaction folders:\n")

for item in INTERACTIONS.iterdir():
    if item.is_dir():
        print(f"[FOLDER] {item.name}")
    else:
        print(f"[FILE]   {item.name}")

EEDI interaction folders:

[FILE]   .DS_Store
[FOLDER] images
[FOLDER] metadata
[FOLDER] test_data
[FOLDER] train_data

In [4]:
TRAIN_DATA = INTERACTIONS / "train_data"

print("Training folder:")
print(TRAIN_DATA)

print("\nTraining files:\n")

for item in TRAIN_DATA.iterdir():
    if item.is_file():
        size_mb = item.stat().st_size / (1024 ** 2)
        print(f"{item.name:<45} {size_mb:>8.2f} MB")
    else:
        print(f"[FOLDER] {item.name}")

Training folder:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets\eedi_interactions\train_data

Training files:

.DS_Store                                         0.01 MB
train_task_1_2.csv                              410.13 MB
train_task_3_4.csv                               30.26 MB

In [5]:
METADATA = INTERACTIONS / "metadata"

print("Metadata folder:")
print(METADATA)

print("\nMetadata files:\n")

for item in METADATA.iterdir():
    if item.is_file():
        size_mb = item.stat().st_size / (1024 ** 2)
        print(f"{item.name:<50} {size_mb:>8.2f} MB")
    else:
        print(f"[FOLDER] {item.name}")

Metadata folder:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets\eedi_interactions\metadata

Metadata files:

answer_metadata_task_1_2.csv                         972.21 MB
answer_metadata_task_3_4.csv                          69.75 MB
question_metadata_task_1_2.csv                         0.71 MB
question_metadata_task_3_4.csv                         0.02 MB
student_metadata_task_1_2.csv                          3.12 MB
student_metadata_task_3_4.csv                          0.13 MB
subject_metadata.csv                                   0.01 MB

In [6]:
TRAIN_FILE = TRAIN_DATA / "train_task_1_2.csv"

print("Loading:")
print(TRAIN_FILE)

train = pd.read_csv(TRAIN_FILE)

print("\nLoaded successfully.")
print("Shape:", train.shape)

Loading:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets\eedi_interactions\train_data\train_task_1_2.csv

Loaded successfully.
Shape: (15867850, 6)

In [7]:
print("Columns:")
print(train.columns.tolist())

print("\nData types:")
print(train.dtypes)

Columns:
['QuestionId', 'UserId', 'AnswerId', 'IsCorrect', 'CorrectAnswer', 'AnswerValue']

Data types:
QuestionId       int64
UserId           int64
AnswerId         int64
IsCorrect        int64
CorrectAnswer    int64
AnswerValue      int64
dtype: object

In [8]:
print("First 5 rows:")
display(train.head())

print("\nLast 5 rows:")
display(train.tail())

First 5 rows:

   QuestionId  UserId  AnswerId  IsCorrect  CorrectAnswer  AnswerValue
0       16997   65967  12453206          0              4            2
1       16531   62121  15686710          1              1            1
2       15911   50013  13598796          0              3            1
3        1701  104909  10511925          0              4            3
4       22896   21748    941747          0              1            4

Last 5 rows:

          QuestionId  UserId  AnswerId  IsCorrect  CorrectAnswer  AnswerValue
15867845       21324  117940  14754537          0              1            4
15867846        9191   62464  17477250          1              1            1
15867847       13091   71308   4786170          1              4            4
15867848       23065   38539  11284982          1              4            4
15867849       22247   44755   9682899          1              3            3

In [9]:
print("Missing values:\n")

missing = train.isnull().sum()

print(missing)

print("\nMissing percentages:\n")

print(
    (missing / len(train) * 100)
    .round(3)
)

Missing values:

QuestionId       0
UserId           0
AnswerId         0
IsCorrect        0
CorrectAnswer    0
AnswerValue      0
dtype: int64

Missing percentages:

QuestionId       0.0
UserId           0.0
AnswerId         0.0
IsCorrect        0.0
CorrectAnswer    0.0
AnswerValue      0.0
dtype: float64

In [10]:
print("Unique values:\n")

for column in train.columns:
    print(
        f"{column:<25} "
        f"{train[column].nunique():,}"
    )

Unique values:

QuestionId                27,613
UserId                    118,971
AnswerId                  15,867,850
IsCorrect                 2
CorrectAnswer             4
AnswerValue               4

In [11]:
# Reduce memory usage

for col in train.columns:
    if train[col].dtype == "int64":
        train[col] = pd.to_numeric(
            train[col],
            downcast="integer"
        )

print("Memory usage after optimization:")
print(
    f"{train.memory_usage(deep=True).sum() / (1024**2):.2f} MB"
)

print("\nData types:")
print(train.dtypes)

Memory usage after optimization:
196.73 MB

Data types:
QuestionId       int16
UserId           int32
AnswerId         int32
IsCorrect         int8
CorrectAnswer     int8
AnswerValue       int8
dtype: object

In [12]:
QUESTION_META = (
    METADATA / "question_metadata_task_1_2.csv"
)

question_meta = pd.read_csv(
    QUESTION_META
)

print("Question metadata shape:", question_meta.shape)

print("\nColumns:")
print(question_meta.columns.tolist())

display(question_meta.head())

Question metadata shape: (27613, 2)

Columns:
['QuestionId', 'SubjectId']

   QuestionId                            SubjectId
0       13090  [3, 32, 71, 77, 141, 185, 186, 214]
1        1855                 [3, 71, 75, 86, 178]
2       10423                     [3, 32, 38, 239]
3        2290                     [3, 32, 33, 144]
4       12785                     [3, 32, 33, 144]

In [13]:
train_questions = set(
    train["QuestionId"].unique()
)

metadata_questions = set(
    question_meta["QuestionId"].unique()
)

missing_questions = (
    train_questions - metadata_questions
)

print("Questions in training:", len(train_questions))
print("Questions in metadata:", len(metadata_questions))
print("Training questions missing metadata:", len(missing_questions))

if len(missing_questions) > 0:
    print("\nSample missing IDs:")
    print(list(missing_questions)[:20])
else:
    print("\nAll training questions have subject metadata.")

Questions in training: 27613
Questions in metadata: 27613
Training questions missing metadata: 0

All training questions have subject metadata.

In [14]:
train = train.merge(
    question_meta[
        ["QuestionId", "SubjectId"]
    ],
    on="QuestionId",
    how="left"
)

print("Shape after merge:", train.shape)

print("\nMissing SubjectIds:")
print(train["SubjectId"].isna().sum())

print("\nSample:")
display(train.head())

Shape after merge: (15867850, 7)

Missing SubjectIds:
0

Sample:

,QuestionId,UserId,AnswerId,IsCorrect,CorrectAnswer,AnswerValue,SubjectId
0,16997,65967,12453206,0,4,2,"[3, 101, 115, 342]"
1,16531,62121,15686710,1,1,1,"[3, 71, 85, 176]"
2,15911,50013,13598796,0,3,1,"[3, 32, 42, 211]"
3,1701,104909,10511925,0,4,3,"[3, 32, 144, 206]"
4,22896,21748,941747,0,1,4,"[3, 32, 144, 203]"

In [15]:
overall_accuracy = train["IsCorrect"].mean()

student_stats = (
    train.groupby("UserId")
    .agg(
        total_attempts=("IsCorrect", "count"),
        correct_answers=("IsCorrect", "sum"),
        accuracy=("IsCorrect", "mean"),
        subjects_attempted=("SubjectId", "nunique"),
        questions_attempted=("QuestionId", "nunique")
    )
    .reset_index()
)

print("Overall answer accuracy:")
print(f"{overall_accuracy:.2%}")

print("\nStudent profiles:", len(student_stats))

print("\nStudent statistics:")
display(
    student_stats.describe()
)

print("\nSample learner profiles:")
display(
    student_stats.head(10)
)

Overall answer accuracy:
64.30%

Student profiles: 118971

Student statistics:

,UserId,total_attempts,correct_answers,accuracy,subjects_attempted,questions_attempted
count,118971.000000,118971.000000,118971.000000,118971.000000,118971.000000,118971.000000
mean,59485.000000,133.375781,85.753999,0.647710,36.125787,133.375781
std,34344.113775,127.762689,86.693154,0.186441,28.762721,127.762689
min,0.000000,29.000000,4.000000,0.094340,1.000000,29.000000
25%,29742.500000,57.000000,36.000000,0.510204,16.000000,57.000000
50%,59485.000000,88.000000,56.000000,0.661417,28.000000,88.000000
75%,89227.500000,159.000000,102.000000,0.795652,46.000000,159.000000
max,118970.000000,2445.000000,1281.000000,1.000000,275.000000,2445.000000

Sample learner profiles:

,UserId,total_attempts,correct_answers,accuracy,subjects_attempted,questions_attempted
0,0,310,139,0.448387,83,310
1,1,60,48,0.800000,34,60
2,2,61,50,0.819672,7,61
3,3,73,55,0.753425,49,73
4,4,61,32,0.524590,30,61
5,5,92,56,0.608696,38,92
6,6,662,284,0.429003,163,662
7,7,61,27,0.442623,23,61
8,8,113,60,0.530973,67,113
9,9,536,400,0.746269,123,536

In [16]:
# Preserve the dataset's interaction order for each learner

train["InteractionIndex"] = (
    train.groupby("UserId")
    .cumcount()
)

train["TotalUserInteractions"] = (
    train.groupby("UserId")["UserId"]
    .transform("size")
)

print("Interaction sequence created.")

display(
    train[
        [
            "UserId",
            "QuestionId",
            "SubjectId",
            "IsCorrect",
            "InteractionIndex",
            "TotalUserInteractions"
        ]
    ].head(10)
)

Interaction sequence created.

,UserId,QuestionId,SubjectId,IsCorrect,InteractionIndex,TotalUserInteractions
0,65967,16997,"[3, 101, 115, 342]",0,0,60
1,62121,16531,"[3, 71, 85, 176]",1,0,86
2,50013,15911,"[3, 32, 42, 211]",0,0,570
3,104909,1701,"[3, 32, 144, 206]",0,0,37
4,21748,22896,"[3, 32, 144, 203]",0,0,151
5,67570,20968,"[3, 32, 39, 230]",1,0,207
6,5257,8826,"[3, 49, 63, 154]",1,0,82
7,82336,9331,"[3, 71, 272, 273]",1,0,135
8,11665,12574,"[3, 71, 86, 178]",1,0,436
9,104459,1383,"[3, 32, 39, 226]",0,0,47

In [17]:
# First 80% of each learner's interactions = history
# Final 20% = prediction/evaluation

train["IsHistory"] = (
    train["InteractionIndex"]
    < train["TotalUserInteractions"] * 0.8
)

history = train[
    train["IsHistory"]
].copy()

validation = train[
    ~train["IsHistory"]
].copy()

print("History interactions:", len(history))
print("Validation interactions:", len(validation))

print(
    f"History ratio: "
    f"{len(history) / len(train):.2%}"
)

print(
    f"Validation ratio: "
    f"{len(validation) / len(train):.2%}"
)

print(
    "\nValidation learners:",
    validation["UserId"].nunique()
)

History interactions: 12741818
Validation interactions: 3126032
History ratio: 80.30%
Validation ratio: 19.70%

Validation learners: 118971

In [18]:
learner_history = (
    history.groupby("UserId")
    .agg(
        history_attempts=("IsCorrect", "count"),
        history_correct=("IsCorrect", "sum"),
        history_accuracy=("IsCorrect", "mean"),
        history_questions=("QuestionId", "nunique"),
        history_subjects=("SubjectId", "nunique")
    )
    .reset_index()
)

print("Learner history profiles:", len(learner_history))

display(
    learner_history.head(10)
)

Learner history profiles: 118971

,UserId,history_attempts,history_correct,history_accuracy,history_questions,history_subjects
0,0,248,114,0.459677,248,80
1,1,48,39,0.812500,48,31
2,2,49,39,0.795918,49,7
3,3,59,47,0.796610,59,42
4,4,49,29,0.591837,49,28
5,5,74,49,0.662162,74,37
6,6,530,229,0.432075,530,154
7,7,49,22,0.448980,49,19
8,8,91,51,0.560440,91,58
9,9,429,314,0.731935,429,113

In [19]:
learner_subject_history = (
    history.groupby(
        ["UserId", "SubjectId"]
    )
    .agg(
        subject_attempts=("IsCorrect", "count"),
        subject_correct=("IsCorrect", "sum"),
        subject_accuracy=("IsCorrect", "mean")
    )
    .reset_index()
)

print(
    "Learner-subject profiles:",
    len(learner_subject_history)
)

display(
    learner_subject_history.head(10)
)

Learner-subject profiles: 3924675

,UserId,SubjectId,subject_attempts,subject_correct,subject_accuracy
0,0,"[3, 101, 111, 348]",6,3,0.50
1,0,"[3, 101, 113, 337]",2,2,1.00
2,0,"[3, 101, 342, 1650]",4,1,0.25
3,0,"[3, 101, 348, 349]",5,2,0.40
4,0,"[3, 101, 348, 350]",3,0,0.00
5,0,"[3, 101, 348, 353]",4,1,0.25
6,0,"[3, 32, 141, 144, 202, 213]",1,0,0.00
7,0,"[3, 32, 141, 144, 204, 213, 216]",2,1,0.50
8,0,"[3, 32, 141, 213]",1,0,0.00
9,0,"[3, 32, 141, 214]",4,3,0.75

In [20]:
question_history = (
    history.groupby("QuestionId")
    .agg(
        question_attempts=("IsCorrect", "count"),
        question_correct=("IsCorrect", "sum"),
        question_accuracy=("IsCorrect", "mean")
    )
    .reset_index()
)

print(
    "Question profiles:",
    len(question_history)
)

display(
    question_history.head(10)
)

Question profiles: 27613

   QuestionId  question_attempts  question_correct  question_accuracy
0           0                545               395           0.724771
1           1                296               218           0.736486
2           2                749               409           0.546061
3           3                 38                38           1.000000
4           4                397               223           0.561713
5           5                833               466           0.559424
6           6               1077               638           0.592386
7           7               1722              1115           0.647503
8           8               1536              1182           0.769531
9           9                140                68           0.485714

In [21]:
# Cell 21 — Fast subject mapping

# SubjectId already represents the question's subject hierarchy.
# We only need a question-level mapping, because the same
# QuestionId always belongs to the same subject hierarchy.

question_subjects = (
    train[["QuestionId", "SubjectId"]]
    .drop_duplicates("QuestionId")
    .copy()
)

print("Unique questions:", len(question_subjects))
print("Columns:", question_subjects.columns.tolist())

display(question_subjects.head(10))

Unique questions: 27613
Columns: ['QuestionId', 'SubjectId']

   QuestionId           SubjectId
0       16997  [3, 101, 115, 342]
1       16531    [3, 71, 85, 176]
2       15911    [3, 32, 42, 211]
3        1701   [3, 32, 144, 206]
4       22896   [3, 32, 144, 203]
5       20968    [3, 32, 39, 230]
6        8826    [3, 49, 63, 154]
7        9331   [3, 71, 272, 273]
8       12574    [3, 71, 86, 178]
9        1383    [3, 32, 39, 226]

In [22]:
# Primary subject = first subject in the EEDI hierarchy

train["PrimarySubjectId"] = train["SubjectList"].apply(
    lambda x: x[0] if len(x) > 0 else -1
)

print(
    "Unique primary subjects:",
    train["PrimarySubjectId"].nunique()
)

display(
    train[
        ["QuestionId", "SubjectList", "PrimarySubjectId"]
    ].head(10)
)

KeyError: 'SubjectList'

In [ ]:
# Merge historical learner statistics into validation interactions

model_data = validation[
    [
        "UserId",
        "QuestionId",
        "SubjectList",
        "PrimarySubjectId",
        "IsCorrect"
    ]
].copy()

model_data = model_data.merge(
    learner_history,
    on="UserId",
    how="left"
)

print("After learner merge:")
print(model_data.shape)

display(model_data.head())

In [ ]:
# Build the learner-subject key using the primary subject

subject_features = learner_subject_history.copy()

subject_features = subject_features.rename(
    columns={
        "SubjectId": "PrimarySubjectId"
    }
)

model_data = model_data.merge(
    subject_features,
    on=["UserId", "PrimarySubjectId"],
    how="left"
)

print("After subject mastery merge:")
print(model_data.shape)

display(
    model_data[
        [
            "UserId",
            "QuestionId",
            "PrimarySubjectId",
            "history_accuracy",
            "subject_attempts",
            "subject_accuracy"
        ]
    ].head(10)
)

In [ ]:
model_data = model_data.merge(
    question_history,
    on="QuestionId",
    how="left"
)

# Fill cases where the learner has never attempted
# the subject before.

model_data["subject_attempts"] = (
    model_data["subject_attempts"].fillna(0)
)

model_data["subject_correct"] = (
    model_data["subject_correct"].fillna(0)
)

model_data["subject_accuracy"] = (
    model_data["subject_accuracy"].fillna(
        model_data["history_accuracy"]
    )
)

# Fill questions with no historical observations
model_data["question_attempts"] = (
    model_data["question_attempts"].fillna(0)
)

model_data["question_correct"] = (
    model_data["question_correct"].fillna(0)
)

model_data["question_accuracy"] = (
    model_data["question_accuracy"].fillna(
        model_data["history_accuracy"]
    )
)

print("Final feature table prepared.")

print("Shape:", model_data.shape)

print("\nMissing values:")
print(
    model_data[
        [
            "history_accuracy",
            "subject_accuracy",
            "question_accuracy"
        ]
    ].isna().sum()
)

display(model_data.head(10))