In [1]:
import pandas as pd
import numpy as np
import joblib

from pathlib import Path

In [2]:
ROOT = Path.cwd().parent

DATASETS = ROOT / "datasets"
INTERACTIONS = DATASETS / "eedi_interactions"

MODELS = ROOT / "models"
MODELS.mkdir(exist_ok=True)

print("Project root:")
print(ROOT)

print("\nEEDI interactions:")
print(INTERACTIONS)

print("\nModels:")
print(MODELS)

Project root:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet

EEDI interactions:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets\eedi_interactions

Models:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\models

In [3]:
print("EEDI interaction folders:\n")

for item in INTERACTIONS.iterdir():
    if item.is_dir():
        print(f"[FOLDER] {item.name}")
    else:
        print(f"[FILE]   {item.name}")

EEDI interaction folders:

[FILE]   .DS_Store
[FOLDER] images
[FOLDER] metadata
[FOLDER] test_data
[FOLDER] train_data

In [4]:
TRAIN_DATA = INTERACTIONS / "train_data"

print("Training folder:")
print(TRAIN_DATA)

print("\nTraining files:\n")

for item in TRAIN_DATA.iterdir():
    if item.is_file():
        size_mb = item.stat().st_size / (1024 ** 2)
        print(f"{item.name:<45} {size_mb:>8.2f} MB")
    else:
        print(f"[FOLDER] {item.name}")

Training folder:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets\eedi_interactions\train_data

Training files:

.DS_Store                                         0.01 MB
train_task_1_2.csv                              410.13 MB
train_task_3_4.csv                               30.26 MB

In [5]:
METADATA = INTERACTIONS / "metadata"

print("Metadata folder:")
print(METADATA)

print("\nMetadata files:\n")

for item in METADATA.iterdir():
    if item.is_file():
        size_mb = item.stat().st_size / (1024 ** 2)
        print(f"{item.name:<50} {size_mb:>8.2f} MB")
    else:
        print(f"[FOLDER] {item.name}")

Metadata folder:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets\eedi_interactions\metadata

Metadata files:

answer_metadata_task_1_2.csv                         972.21 MB
answer_metadata_task_3_4.csv                          69.75 MB
question_metadata_task_1_2.csv                         0.71 MB
question_metadata_task_3_4.csv                         0.02 MB
student_metadata_task_1_2.csv                          3.12 MB
student_metadata_task_3_4.csv                          0.13 MB
subject_metadata.csv                                   0.01 MB

In [6]:
TRAIN_FILE = TRAIN_DATA / "train_task_1_2.csv"

print("Loading:")
print(TRAIN_FILE)

train = pd.read_csv(TRAIN_FILE)

print("\nLoaded successfully.")
print("Shape:", train.shape)

Loading:
c:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\datasets\eedi_interactions\train_data\train_task_1_2.csv

Loaded successfully.
Shape: (15867850, 6)

In [7]:
print("Columns:")
print(train.columns.tolist())

print("\nData types:")
print(train.dtypes)

Columns:
['QuestionId', 'UserId', 'AnswerId', 'IsCorrect', 'CorrectAnswer', 'AnswerValue']

Data types:
QuestionId       int64
UserId           int64
AnswerId         int64
IsCorrect        int64
CorrectAnswer    int64
AnswerValue      int64
dtype: object

In [8]:
print("First 5 rows:")
display(train.head())

print("\nLast 5 rows:")
display(train.tail())

First 5 rows:

   QuestionId  UserId  AnswerId  IsCorrect  CorrectAnswer  AnswerValue
0       16997   65967  12453206          0              4            2
1       16531   62121  15686710          1              1            1
2       15911   50013  13598796          0              3            1
3        1701  104909  10511925          0              4            3
4       22896   21748    941747          0              1            4

Last 5 rows:

          QuestionId  UserId  AnswerId  IsCorrect  CorrectAnswer  AnswerValue
15867845       21324  117940  14754537          0              1            4
15867846        9191   62464  17477250          1              1            1
15867847       13091   71308   4786170          1              4            4
15867848       23065   38539  11284982          1              4            4
15867849       22247   44755   9682899          1              3            3

In [9]:
print("Missing values:\n")

missing = train.isnull().sum()

print(missing)

print("\nMissing percentages:\n")

print(
    (missing / len(train) * 100)
    .round(3)
)

Missing values:

QuestionId       0
UserId           0
AnswerId         0
IsCorrect        0
CorrectAnswer    0
AnswerValue      0
dtype: int64

Missing percentages:

QuestionId       0.0
UserId           0.0
AnswerId         0.0
IsCorrect        0.0
CorrectAnswer    0.0
AnswerValue      0.0
dtype: float64

In [10]:
print("Unique values:\n")

for column in train.columns:
    print(
        f"{column:<25} "
        f"{train[column].nunique():,}"
    )

Unique values:

QuestionId                27,613
UserId                    118,971
AnswerId                  15,867,850
IsCorrect                 2
CorrectAnswer             4
AnswerValue               4

In [11]:
# Reduce memory usage

for col in train.columns:
    if train[col].dtype == "int64":
        train[col] = pd.to_numeric(
            train[col],
            downcast="integer"
        )

print("Memory usage after optimization:")
print(
    f"{train.memory_usage(deep=True).sum() / (1024**2):.2f} MB"
)

print("\nData types:")
print(train.dtypes)

Memory usage after optimization:
196.73 MB

Data types:
QuestionId       int16
UserId           int32
AnswerId         int32
IsCorrect         int8
CorrectAnswer     int8
AnswerValue       int8
dtype: object

In [12]:
QUESTION_META = (
    METADATA / "question_metadata_task_1_2.csv"
)

question_meta = pd.read_csv(
    QUESTION_META
)

print("Question metadata shape:", question_meta.shape)

print("\nColumns:")
print(question_meta.columns.tolist())

display(question_meta.head())

Question metadata shape: (27613, 2)

Columns:
['QuestionId', 'SubjectId']

   QuestionId                            SubjectId
0       13090  [3, 32, 71, 77, 141, 185, 186, 214]
1        1855                 [3, 71, 75, 86, 178]
2       10423                     [3, 32, 38, 239]
3        2290                     [3, 32, 33, 144]
4       12785                     [3, 32, 33, 144]

In [13]:
train_questions = set(
    train["QuestionId"].unique()
)

metadata_questions = set(
    question_meta["QuestionId"].unique()
)

missing_questions = (
    train_questions - metadata_questions
)

print("Questions in training:", len(train_questions))
print("Questions in metadata:", len(metadata_questions))
print("Training questions missing metadata:", len(missing_questions))

if len(missing_questions) > 0:
    print("\nSample missing IDs:")
    print(list(missing_questions)[:20])
else:
    print("\nAll training questions have subject metadata.")

Questions in training: 27613
Questions in metadata: 27613
Training questions missing metadata: 0

All training questions have subject metadata.

In [14]:
train = train.merge(
    question_meta[
        ["QuestionId", "SubjectId"]
    ],
    on="QuestionId",
    how="left"
)

print("Shape after merge:", train.shape)

print("\nMissing SubjectIds:")
print(train["SubjectId"].isna().sum())

print("\nSample:")
display(train.head())

Shape after merge: (15867850, 7)

Missing SubjectIds:
0

Sample:

,QuestionId,UserId,AnswerId,IsCorrect,CorrectAnswer,AnswerValue,SubjectId
0,16997,65967,12453206,0,4,2,"[3, 101, 115, 342]"
1,16531,62121,15686710,1,1,1,"[3, 71, 85, 176]"
2,15911,50013,13598796,0,3,1,"[3, 32, 42, 211]"
3,1701,104909,10511925,0,4,3,"[3, 32, 144, 206]"
4,22896,21748,941747,0,1,4,"[3, 32, 144, 203]"

In [15]:
overall_accuracy = train["IsCorrect"].mean()

student_stats = (
    train.groupby("UserId")
    .agg(
        total_attempts=("IsCorrect", "count"),
        correct_answers=("IsCorrect", "sum"),
        accuracy=("IsCorrect", "mean"),
        subjects_attempted=("SubjectId", "nunique"),
        questions_attempted=("QuestionId", "nunique")
    )
    .reset_index()
)

print("Overall answer accuracy:")
print(f"{overall_accuracy:.2%}")

print("\nStudent profiles:", len(student_stats))

print("\nStudent statistics:")
display(
    student_stats.describe()
)

print("\nSample learner profiles:")
display(
    student_stats.head(10)
)

Overall answer accuracy:
64.30%

Student profiles: 118971

Student statistics:

,UserId,total_attempts,correct_answers,accuracy,subjects_attempted,questions_attempted
count,118971.000000,118971.000000,118971.000000,118971.000000,118971.000000,118971.000000
mean,59485.000000,133.375781,85.753999,0.647710,36.125787,133.375781
std,34344.113775,127.762689,86.693154,0.186441,28.762721,127.762689
min,0.000000,29.000000,4.000000,0.094340,1.000000,29.000000
25%,29742.500000,57.000000,36.000000,0.510204,16.000000,57.000000
50%,59485.000000,88.000000,56.000000,0.661417,28.000000,88.000000
75%,89227.500000,159.000000,102.000000,0.795652,46.000000,159.000000
max,118970.000000,2445.000000,1281.000000,1.000000,275.000000,2445.000000

Sample learner profiles:

,UserId,total_attempts,correct_answers,accuracy,subjects_attempted,questions_attempted
0,0,310,139,0.448387,83,310
1,1,60,48,0.800000,34,60
2,2,61,50,0.819672,7,61
3,3,73,55,0.753425,49,73
4,4,61,32,0.524590,30,61
5,5,92,56,0.608696,38,92
6,6,662,284,0.429003,163,662
7,7,61,27,0.442623,23,61
8,8,113,60,0.530973,67,113
9,9,536,400,0.746269,123,536

In [16]:
# Preserve the dataset's interaction order for each learner

train["InteractionIndex"] = (
    train.groupby("UserId")
    .cumcount()
)

train["TotalUserInteractions"] = (
    train.groupby("UserId")["UserId"]
    .transform("size")
)

print("Interaction sequence created.")

display(
    train[
        [
            "UserId",
            "QuestionId",
            "SubjectId",
            "IsCorrect",
            "InteractionIndex",
            "TotalUserInteractions"
        ]
    ].head(10)
)

Interaction sequence created.

,UserId,QuestionId,SubjectId,IsCorrect,InteractionIndex,TotalUserInteractions
0,65967,16997,"[3, 101, 115, 342]",0,0,60
1,62121,16531,"[3, 71, 85, 176]",1,0,86
2,50013,15911,"[3, 32, 42, 211]",0,0,570
3,104909,1701,"[3, 32, 144, 206]",0,0,37
4,21748,22896,"[3, 32, 144, 203]",0,0,151
5,67570,20968,"[3, 32, 39, 230]",1,0,207
6,5257,8826,"[3, 49, 63, 154]",1,0,82
7,82336,9331,"[3, 71, 272, 273]",1,0,135
8,11665,12574,"[3, 71, 86, 178]",1,0,436
9,104459,1383,"[3, 32, 39, 226]",0,0,47

In [17]:
# First 80% of each learner's interactions = history
# Final 20% = prediction/evaluation

train["IsHistory"] = (
    train["InteractionIndex"]
    < train["TotalUserInteractions"] * 0.8
)

history = train[
    train["IsHistory"]
].copy()

validation = train[
    ~train["IsHistory"]
].copy()

print("History interactions:", len(history))
print("Validation interactions:", len(validation))

print(
    f"History ratio: "
    f"{len(history) / len(train):.2%}"
)

print(
    f"Validation ratio: "
    f"{len(validation) / len(train):.2%}"
)

print(
    "\nValidation learners:",
    validation["UserId"].nunique()
)

History interactions: 12741818
Validation interactions: 3126032
History ratio: 80.30%
Validation ratio: 19.70%

Validation learners: 118971

In [18]:
learner_history = (
    history.groupby("UserId")
    .agg(
        history_attempts=("IsCorrect", "count"),
        history_correct=("IsCorrect", "sum"),
        history_accuracy=("IsCorrect", "mean"),
        history_questions=("QuestionId", "nunique"),
        history_subjects=("SubjectId", "nunique")
    )
    .reset_index()
)

print("Learner history profiles:", len(learner_history))

display(
    learner_history.head(10)
)

Learner history profiles: 118971

,UserId,history_attempts,history_correct,history_accuracy,history_questions,history_subjects
0,0,248,114,0.459677,248,80
1,1,48,39,0.812500,48,31
2,2,49,39,0.795918,49,7
3,3,59,47,0.796610,59,42
4,4,49,29,0.591837,49,28
5,5,74,49,0.662162,74,37
6,6,530,229,0.432075,530,154
7,7,49,22,0.448980,49,19
8,8,91,51,0.560440,91,58
9,9,429,314,0.731935,429,113

In [19]:
learner_subject_history = (
    history.groupby(
        ["UserId", "SubjectId"]
    )
    .agg(
        subject_attempts=("IsCorrect", "count"),
        subject_correct=("IsCorrect", "sum"),
        subject_accuracy=("IsCorrect", "mean")
    )
    .reset_index()
)

print(
    "Learner-subject profiles:",
    len(learner_subject_history)
)

display(
    learner_subject_history.head(10)
)

Learner-subject profiles: 3924675

,UserId,SubjectId,subject_attempts,subject_correct,subject_accuracy
0,0,"[3, 101, 111, 348]",6,3,0.50
1,0,"[3, 101, 113, 337]",2,2,1.00
2,0,"[3, 101, 342, 1650]",4,1,0.25
3,0,"[3, 101, 348, 349]",5,2,0.40
4,0,"[3, 101, 348, 350]",3,0,0.00
5,0,"[3, 101, 348, 353]",4,1,0.25
6,0,"[3, 32, 141, 144, 202, 213]",1,0,0.00
7,0,"[3, 32, 141, 144, 204, 213, 216]",2,1,0.50
8,0,"[3, 32, 141, 213]",1,0,0.00
9,0,"[3, 32, 141, 214]",4,3,0.75

In [20]:
question_history = (
    history.groupby("QuestionId")
    .agg(
        question_attempts=("IsCorrect", "count"),
        question_correct=("IsCorrect", "sum"),
        question_accuracy=("IsCorrect", "mean")
    )
    .reset_index()
)

print(
    "Question profiles:",
    len(question_history)
)

display(
    question_history.head(10)
)

Question profiles: 27613

   QuestionId  question_attempts  question_correct  question_accuracy
0           0                545               395           0.724771
1           1                296               218           0.736486
2           2                749               409           0.546061
3           3                 38                38           1.000000
4           4                397               223           0.561713
5           5                833               466           0.559424
6           6               1077               638           0.592386
7           7               1722              1115           0.647503
8           8               1536              1182           0.769531
9           9                140                68           0.485714

In [21]:
# Cell 21 — Fast subject mapping

# SubjectId already represents the question's subject hierarchy.
# We only need a question-level mapping, because the same
# QuestionId always belongs to the same subject hierarchy.

question_subjects = (
    train[["QuestionId", "SubjectId"]]
    .drop_duplicates("QuestionId")
    .copy()
)

print("Unique questions:", len(question_subjects))
print("Columns:", question_subjects.columns.tolist())

display(question_subjects.head(10))

Unique questions: 27613
Columns: ['QuestionId', 'SubjectId']

   QuestionId           SubjectId
0       16997  [3, 101, 115, 342]
1       16531    [3, 71, 85, 176]
2       15911    [3, 32, 42, 211]
3        1701   [3, 32, 144, 206]
4       22896   [3, 32, 144, 203]
5       20968    [3, 32, 39, 230]
6        8826    [3, 49, 63, 154]
7        9331   [3, 71, 272, 273]
8       12574    [3, 71, 86, 178]
9        1383    [3, 32, 39, 226]

In [23]:
# Cell 22 — Create primary subject from the question-level mapping

def get_primary_subject(value):
    if isinstance(value, (list, tuple)):
        return value[0] if len(value) > 0 else -1

    if isinstance(value, str):
        try:
            value = value.strip("[]")
            parts = [x.strip() for x in value.split(",") if x.strip()]
            return int(parts[0]) if parts else -1
        except:
            return -1

    if pd.notna(value):
        return int(value)

    return -1


question_subjects["PrimarySubjectId"] = (
    question_subjects["SubjectId"]
    .apply(get_primary_subject)
)

print("Question mappings:", len(question_subjects))
print(
    "Unique primary subjects:",
    question_subjects["PrimarySubjectId"].nunique()
)

print("\nSample mappings:")
display(
    question_subjects[
        ["QuestionId", "SubjectId", "PrimarySubjectId"]
    ].head(10)
)

Question mappings: 27613
Unique primary subjects: 1

Sample mappings:

   QuestionId           SubjectId  PrimarySubjectId
0       16997  [3, 101, 115, 342]                 3
1       16531    [3, 71, 85, 176]                 3
2       15911    [3, 32, 42, 211]                 3
3        1701   [3, 32, 144, 206]                 3
4       22896   [3, 32, 144, 203]                 3
5       20968    [3, 32, 39, 230]                 3
6        8826    [3, 49, 63, 154]                 3
7        9331   [3, 71, 272, 273]                 3
8       12574    [3, 71, 86, 178]                 3
9        1383    [3, 32, 39, 226]                 3

In [24]:
# Cell 23 — Create model feature table

model_data = validation[
    [
        "UserId",
        "QuestionId",
        "SubjectId",
        "IsCorrect"
    ]
].copy()

# Attach learner-level historical performance
model_data = model_data.merge(
    learner_history,
    on="UserId",
    how="left"
)

print("Model data after learner features:")
print(model_data.shape)

print("\nColumns:")
print(model_data.columns.tolist())

display(model_data.head(10))

Model data after learner features:
(3126032, 9)

Columns:
['UserId', 'QuestionId', 'SubjectId', 'IsCorrect', 'history_attempts', 'history_correct', 'history_accuracy', 'history_questions', 'history_subjects']

,UserId,QuestionId,SubjectId,IsCorrect,history_attempts,history_correct,history_accuracy,history_questions,history_subjects
0,14038,26591,"[3, 71, 73, 74]",1,36,30,0.833333,36,17
1,14038,2803,"[3, 32, 39, 229]",0,36,30,0.833333,36,17
2,65509,3455,"[3, 49, 64, 154]",1,40,26,0.650000,40,10
3,65191,13917,"[3, 101, 102, 338]",1,45,36,0.800000,45,22
4,65145,5606,"[3, 32, 40, 47]",1,36,31,0.861111,36,8
5,77619,13702,"[3, 71, 77, 184]",1,50,34,0.680000,50,20
6,27056,20389,"[3, 49, 54, 257]",0,32,10,0.312500,32,15
7,65191,16902,"[3, 32, 46, 242]",1,45,36,0.800000,45,22
8,30125,19213,"[3, 71, 74, 181]",1,32,18,0.562500,32,20
9,81862,8100,"[3, 71, 77, 187]",1,34,24,0.705882,34,33

In [27]:
# Cell 24 — Parse subject hierarchy and extract most specific subject

import ast

def get_specific_subject(value):
    if isinstance(value, (list, tuple)):
        return int(value[-1]) if len(value) > 0 else -1

    if isinstance(value, str):
        try:
            parsed = ast.literal_eval(value)

            if isinstance(parsed, (list, tuple)):
                return int(parsed[-1]) if len(parsed) > 0 else -1

            return int(parsed)

        except (ValueError, SyntaxError, TypeError):
            return -1

    if pd.notna(value):
        return int(value)

    return -1


# Create the specific subject
question_subjects["PrimarySubjectId"] = (
    question_subjects["SubjectId"]
    .apply(get_specific_subject)
)

# Remove previous incorrect mapping
model_data = model_data.drop(
    columns=["PrimarySubjectId"],
    errors="ignore"
)

# Merge correct mapping
model_data = model_data.merge(
    question_subjects[
        ["QuestionId", "PrimarySubjectId"]
    ],
    on="QuestionId",
    how="left"
)

print("Model data:")
print(model_data.shape)

print("\nMissing specific subjects:")
print(model_data["PrimarySubjectId"].isna().sum())

print("\nInvalid subjects (-1):")
print((model_data["PrimarySubjectId"] == -1).sum())

print("\nUnique specific subjects:")
print(model_data["PrimarySubjectId"].nunique())

print("\nSample:")
display(
    model_data[
        [
            "QuestionId",
            "SubjectId",
            "PrimarySubjectId",
            "history_accuracy"
        ]
    ].head(10)
)

Model data:
(3126032, 10)

Missing specific subjects:
0

Invalid subjects (-1):
0

Unique specific subjects:
282

Sample:

   QuestionId           SubjectId  PrimarySubjectId  history_accuracy
0       26591     [3, 71, 73, 74]                74          0.833333
1        2803    [3, 32, 39, 229]               229          0.833333
2        3455    [3, 49, 64, 154]               154          0.650000
3       13917  [3, 101, 102, 338]               338          0.800000
4        5606     [3, 32, 40, 47]                47          0.861111
5       13702    [3, 71, 77, 184]               184          0.680000
6       20389    [3, 49, 54, 257]               257          0.312500
7       16902    [3, 32, 46, 242]               242          0.800000
8       19213    [3, 71, 74, 181]               181          0.562500
9        8100    [3, 71, 77, 187]               187          0.705882

In [30]:
# ============================================================
# CELL 29 — FIX + MERGE SUBJECT FEATURES
# ============================================================

print("model_data columns:")
print(model_data.columns.tolist())

print("\nsubject_features columns:")
print(subject_features.columns.tolist())


# ------------------------------------------------------------
# 1. Make sure PrimarySubjectId exists in subject_features
# ------------------------------------------------------------

if "PrimarySubjectId" not in subject_features.columns:

    # Try common alternative names
    possible_subject_cols = [
        "SubjectId",
        "SpecificSubjectId",
        "SubjectID",
        "subject_id",
        "primary_subject_id"
    ]

    found = None

    for col in possible_subject_cols:
        if col in subject_features.columns:
            found = col
            break

    if found is not None:
        subject_features = subject_features.rename(
            columns={found: "PrimarySubjectId"}
        )
        print(f"\nRenamed '{found}' -> 'PrimarySubjectId'")

    else:
        raise KeyError(
            "Could not find a subject ID column in subject_features. "
            f"Available columns: {subject_features.columns.tolist()}"
        )


# ------------------------------------------------------------
# 2. Normalize merge key types
# ------------------------------------------------------------

model_data["PrimarySubjectId"] = pd.to_numeric(
    model_data["PrimarySubjectId"],
    errors="coerce"
)

subject_features["PrimarySubjectId"] = pd.to_numeric(
    subject_features["PrimarySubjectId"],
    errors="coerce"
)


# Remove invalid IDs
model_data = model_data[
    model_data["PrimarySubjectId"].notna()
].copy()

subject_features = subject_features[
    subject_features["PrimarySubjectId"].notna()
].copy()


# Convert to normal int64
model_data["PrimarySubjectId"] = (
    model_data["PrimarySubjectId"].astype("int64")
)

subject_features["PrimarySubjectId"] = (
    subject_features["PrimarySubjectId"].astype("int64")
)


# ------------------------------------------------------------
# 3. Remove old subject feature columns if they already exist
# ------------------------------------------------------------

subject_cols = [
    "subject_attempts",
    "subject_correct",
    "subject_accuracy"
]

for col in subject_cols:
    if col in model_data.columns:
        model_data.drop(columns=col, inplace=True)


# ------------------------------------------------------------
# 4. Keep only required subject features
# ------------------------------------------------------------

subject_features = subject_features[
    [
        "UserId",
        "PrimarySubjectId",
        "subject_attempts",
        "subject_correct",
        "subject_accuracy"
    ]
].copy()


# ------------------------------------------------------------
# 5. Normalize UserId too
# ------------------------------------------------------------

model_data["UserId"] = pd.to_numeric(
    model_data["UserId"],
    errors="coerce"
).astype("int64")

subject_features["UserId"] = pd.to_numeric(
    subject_features["UserId"],
    errors="coerce"
).astype("int64")


# ------------------------------------------------------------
# 6. Merge
# ------------------------------------------------------------

model_data = model_data.merge(
    subject_features,
    on=["UserId", "PrimarySubjectId"],
    how="left"
)


# ------------------------------------------------------------
# 7. Fill missing subject statistics
# ------------------------------------------------------------

model_data["subject_attempts"] = (
    model_data["subject_attempts"].fillna(0)
)

model_data["subject_correct"] = (
    model_data["subject_correct"].fillna(0)
)

model_data["subject_accuracy"] = (
    model_data["subject_accuracy"].fillna(0.0)
)


# ------------------------------------------------------------
# 8. Verify
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("SUBJECT FEATURES MERGED")
print("=" * 60)

print("Model data shape:", model_data.shape)

print("\nColumns:")
print(model_data.columns.tolist())

print("\nMissing subject features:")
print(
    model_data[
        ["subject_attempts", "subject_correct", "subject_accuracy"]
    ].isna().sum()
)

print("\nSample:")
display(
    model_data[
        [
            "UserId",
            "QuestionId",
            "PrimarySubjectId",
            "history_accuracy",
            "subject_attempts",
            "subject_correct",
            "subject_accuracy"
        ]
    ].head(10)
)

model_data columns:
['UserId', 'QuestionId', 'SubjectId', 'IsCorrect', 'history_attempts', 'history_correct', 'history_accuracy', 'history_questions', 'history_subjects', 'PrimarySubjectId']

subject_features columns:
['UserId', 'SubjectId', 'subject_attempts', 'subject_correct', 'subject_accuracy']

Renamed 'SubjectId' -> 'PrimarySubjectId'

============================================================
SUBJECT FEATURES MERGED
============================================================
Model data shape: (3126032, 13)

Columns:
['UserId', 'QuestionId', 'SubjectId', 'IsCorrect', 'history_attempts', 'history_correct', 'history_accuracy', 'history_questions', 'history_subjects', 'PrimarySubjectId', 'subject_attempts', 'subject_correct', 'subject_accuracy']

Missing subject features:
subject_attempts    0
subject_correct     0
subject_accuracy    0
dtype: int64

Sample:

,UserId,QuestionId,PrimarySubjectId,history_accuracy,subject_attempts,subject_correct,subject_accuracy
0,14038,26591,74,0.833333,0.0,0.0,0.0
1,14038,2803,229,0.833333,0.0,0.0,0.0
2,65509,3455,154,0.650000,0.0,0.0,0.0
3,65191,13917,338,0.800000,0.0,0.0,0.0
4,65145,5606,47,0.861111,0.0,0.0,0.0
5,77619,13702,184,0.680000,0.0,0.0,0.0
6,27056,20389,257,0.312500,0.0,0.0,0.0
7,65191,16902,242,0.800000,0.0,0.0,0.0
8,30125,19213,181,0.562500,0.0,0.0,0.0
9,81862,8100,187,0.705882,0.0,0.0,0.0

In [33]:
# ============================================================
# CELL 26 — VERIFY SUBJECT FEATURE KEY
# ============================================================

print("model_data SubjectId:")
print("dtype:", model_data["SubjectId"].dtype)
print("sample:", model_data["SubjectId"].head(5).tolist())

print("\nlearner_subject_history SubjectId:")
print("dtype:", learner_subject_history["SubjectId"].dtype)
print("sample:", learner_subject_history["SubjectId"].head(5).tolist())

print("\nUserId dtypes:")
print("model_data:", model_data["UserId"].dtype)
print("learner_subject_history:", learner_subject_history["UserId"].dtype)

model_data SubjectId:
dtype: str
sample: ['[3, 71, 73, 74]', '[3, 32, 39, 229]', '[3, 49, 64, 154]', '[3, 101, 102, 338]', '[3, 32, 40, 47]']

learner_subject_history SubjectId:
dtype: str
sample: ['[3, 101, 111, 348]', '[3, 101, 113, 337]', '[3, 101, 342, 1650]', '[3, 101, 348, 349]', '[3, 101, 348, 350]']

UserId dtypes:
model_data: int64
learner_subject_history: int32

In [34]:
# ============================================================
# CELL 27 — BUILD USER × SPECIFIC-SUBJECT FEATURES
# ============================================================

import re

# Work from the already-created learner subject history
subject_features = learner_subject_history.copy()

# Extract the final subject ID from the hierarchy
subject_features["SpecificSubjectId"] = (
    subject_features["SubjectId"]
    .str.extract(r',\s*(\d+)\]$')[0]
    .astype("int64")
)

print("Subject features before aggregation:")
print(subject_features.shape)

print("\nUnique specific subjects:")
print(subject_features["SpecificSubjectId"].nunique())

# Aggregate in case multiple subject-paths map to the same
# specific subject for the same learner
subject_features = (
    subject_features
    .groupby(
        ["UserId", "SpecificSubjectId"],
        as_index=False
    )
    .agg(
        subject_attempts=("subject_attempts", "sum"),
        subject_correct=("subject_correct", "sum")
    )
)

# Recalculate accuracy from aggregated counts
subject_features["subject_accuracy"] = (
    subject_features["subject_correct"]
    / subject_features["subject_attempts"].replace(0, 1)
)

print("\nSubject features after aggregation:")
print(subject_features.shape)

print("\nUnique learners:")
print(subject_features["UserId"].nunique())

print("\nUnique specific subjects:")
print(subject_features["SpecificSubjectId"].nunique())

print("\nSample:")
display(subject_features.head(10))

Subject features before aggregation:
(3924675, 6)

Unique specific subjects:
282

Subject features after aggregation:
(3256952, 5)

Unique learners:
118971

Unique specific subjects:
282

Sample:

,UserId,SpecificSubjectId,subject_attempts,subject_correct,subject_accuracy
0,0,47,13,6,0.461538
1,0,141,8,2,0.250000
2,0,152,3,1,0.333333
3,0,153,2,0,0.000000
4,0,156,7,1,0.142857
5,0,165,6,4,0.666667
6,0,166,7,6,0.857143
7,0,167,2,0,0.000000
8,0,168,7,2,0.285714
9,0,178,14,7,0.500000

In [35]:
# ============================================================
# CELL 28 — MERGE SPECIFIC SUBJECT FEATURES
# ============================================================

# Extract the specific subject ID from the validation question's
# subject hierarchy
model_data["SpecificSubjectId"] = (
    model_data["SubjectId"]
    .str.extract(r',\s*(\d+)\]$')[0]
    .astype("int64")
)

print("Model data specific subjects:")
print(model_data["SpecificSubjectId"].nunique())

# Remove the previously broken subject feature columns
old_subject_cols = [
    "PrimarySubjectId",
    "subject_attempts",
    "subject_correct",
    "subject_accuracy"
]

for col in old_subject_cols:
    if col in model_data.columns:
        model_data.drop(columns=col, inplace=True)


# Merge learner × specific-subject history
model_data = model_data.merge(
    subject_features[
        [
            "UserId",
            "SpecificSubjectId",
            "subject_attempts",
            "subject_correct",
            "subject_accuracy"
        ]
    ],
    on=["UserId", "SpecificSubjectId"],
    how="left"
)


# Learners with no previous history for this specific subject
missing_subject_history = (
    model_data["subject_attempts"].isna().sum()
)

print("\nMissing subject history:")
print(missing_subject_history)

print(
    "Missing percentage:",
    f"{missing_subject_history / len(model_data) * 100:.2f}%"
)


# Fill unseen learner-subject combinations
model_data["subject_attempts"] = (
    model_data["subject_attempts"].fillna(0)
)

model_data["subject_correct"] = (
    model_data["subject_correct"].fillna(0)
)

model_data["subject_accuracy"] = (
    model_data["subject_accuracy"].fillna(0.0)
)


print("\nModel data shape:")
print(model_data.shape)

print("\nColumns:")
print(model_data.columns.tolist())

print("\nSample:")
display(
    model_data[
        [
            "UserId",
            "QuestionId",
            "SpecificSubjectId",
            "history_attempts",
            "history_accuracy",
            "subject_attempts",
            "subject_correct",
            "subject_accuracy",
            "IsCorrect"
        ]
    ].head(10)
)

Model data specific subjects:
282

Missing subject history:
282284
Missing percentage: 9.03%

Model data shape:
(3126032, 13)

Columns:
['UserId', 'QuestionId', 'SubjectId', 'IsCorrect', 'history_attempts', 'history_correct', 'history_accuracy', 'history_questions', 'history_subjects', 'SpecificSubjectId', 'subject_attempts', 'subject_correct', 'subject_accuracy']

Sample:

,UserId,QuestionId,SpecificSubjectId,history_attempts,history_accuracy,subject_attempts,subject_correct,subject_accuracy,IsCorrect
0,14038,26591,74,36,0.833333,6.0,6.0,1.000000,1
1,14038,2803,229,36,0.833333,1.0,1.0,1.000000,0
2,65509,3455,154,40,0.650000,10.0,9.0,0.900000,1
3,65191,13917,338,45,0.800000,9.0,9.0,1.000000,1
4,65145,5606,47,36,0.861111,10.0,9.0,0.900000,1
5,77619,13702,184,50,0.680000,10.0,8.0,0.800000,1
6,27056,20389,257,32,0.312500,2.0,0.0,0.000000,0
7,65191,16902,242,45,0.800000,6.0,4.0,0.666667,1
8,30125,19213,181,32,0.562500,2.0,1.0,0.500000,1
9,81862,8100,187,34,0.705882,0.0,0.0,0.000000,1

In [38]:
# ============================================================
# CELL 29 — ADD QUESTION DIFFICULTY FEATURES
# ============================================================

question_features = question_history[
    [
        "QuestionId",
        "question_attempts",
        "question_correct",
        "question_accuracy"
    ]
].copy()

# Ensure matching key type
model_data["QuestionId"] = model_data["QuestionId"].astype("int64")
question_features["QuestionId"] = question_features["QuestionId"].astype("int64")

# Merge historical question performance
model_data = model_data.merge(
    question_features,
    on="QuestionId",
    how="left"
)

# Questions with no historical attempts
model_data["question_attempts"] = (
    model_data["question_attempts"].fillna(0)
)

model_data["question_correct"] = (
    model_data["question_correct"].fillna(0)
)

model_data["question_accuracy"] = (
    model_data["question_accuracy"].fillna(0.0)
)

print("=" * 60)
print("QUESTION FEATURES MERGED")
print("=" * 60)

print("Model data shape:", model_data.shape)

print("\nMissing question features:")
print(
    model_data[
        [
            "question_attempts",
            "question_correct",
            "question_accuracy"
        ]
    ].isna().sum()
)

print("\nSample:")
display(
    model_data[
        [
            "UserId",
            "QuestionId",
            "SpecificSubjectId",
            "history_attempts",
            "history_accuracy",
            "subject_attempts",
            "subject_accuracy",
            "question_attempts",
            "question_accuracy",
            "IsCorrect"
        ]
    ].head(10)
)

============================================================
QUESTION FEATURES MERGED
============================================================
Model data shape: (3126032, 16)

Missing question features:
question_attempts    0
question_correct     0
question_accuracy    0
dtype: int64

Sample:

,UserId,QuestionId,SpecificSubjectId,history_attempts,history_accuracy,subject_attempts,subject_accuracy,question_attempts,question_accuracy,IsCorrect
0,14038,26591,74,36,0.833333,6.0,1.000000,682,0.844575,1
1,14038,2803,229,36,0.833333,1.0,1.000000,942,0.757962,0
2,65509,3455,154,40,0.650000,10.0,0.900000,901,0.800222,1
3,65191,13917,338,45,0.800000,9.0,1.000000,475,0.852632,1
4,65145,5606,47,36,0.861111,10.0,0.900000,1346,0.725854,1
5,77619,13702,184,50,0.680000,10.0,0.800000,292,0.876712,1
6,27056,20389,257,32,0.312500,2.0,0.000000,1166,0.573756,0
7,65191,16902,242,45,0.800000,6.0,0.666667,247,0.623482,1
8,30125,19213,181,32,0.562500,2.0,0.500000,3028,0.845773,1
9,81862,8100,187,34,0.705882,0.0,0.000000,2361,0.734435,1

In [39]:
# ============================================================
# CELL 30 — TRAIN LEARNER PERFORMANCE MODEL
# ============================================================

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, roc_auc_score

print("=" * 60)
print("PREPARING CORRECTNESS MODEL")
print("=" * 60)

# Numerical behavioral features
FEATURES = [
    "IsCorrect",  # temporary target, removed below
    "history_attempts",
    "history_correct",
    "history_accuracy",
    "history_questions",
    "history_subjects",
    "subject_attempts",
    "subject_correct",
    "subject_accuracy",
    "question_attempts",
    "question_correct",
    "question_accuracy"
]

# Target
y = model_data["IsCorrect"].astype("int8")

# Remove target
feature_cols = [f for f in FEATURES if f != "IsCorrect"]

X = model_data[feature_cols].copy()

print("Features used:")
print(feature_cols)

print("\nTraining matrix:", X.shape)
print("Target distribution:")
print(y.value_counts(normalize=True))

# ------------------------------------------------------------
# TRAIN MODEL
# ------------------------------------------------------------

correctness_model = HistGradientBoostingClassifier(
    learning_rate=0.08,
    max_iter=150,
    max_leaf_nodes=31,
    min_samples_leaf=100,
    l2_regularization=1.0,
    random_state=42
)

print("\nTraining correctness model...")

correctness_model.fit(X, y)

print("\nCorrectness model trained successfully.")

============================================================
PREPARING CORRECTNESS MODEL
============================================================
Features used:
['history_attempts', 'history_correct', 'history_accuracy', 'history_questions', 'history_subjects', 'subject_attempts', 'subject_correct', 'subject_accuracy', 'question_attempts', 'question_correct', 'question_accuracy']

Training matrix: (3126032, 11)
Target distribution:
IsCorrect
1    0.642609
0    0.357391
Name: proportion, dtype: float64

Training correctness model...

Correctness model trained successfully.

In [40]:
# ============================================================
# CELL 31 — EVALUATE CORRECTNESS MODEL
# ============================================================

print("=" * 60)
print("EVALUATING CORRECTNESS MODEL")
print("=" * 60)

# Predictions
correctness_pred = correctness_model.predict(X)
correctness_prob = correctness_model.predict_proba(X)[:, 1]

# Metrics
accuracy = accuracy_score(y, correctness_pred)
auc = roc_auc_score(y, correctness_prob)

print(f"\nAccuracy: {accuracy:.4f} ({accuracy * 100:.2f}%)")
print(f"ROC-AUC:  {auc:.4f}")

print("\nPrediction distribution:")
print(
    pd.Series(correctness_pred)
    .value_counts()
    .sort_index()
)

print("\nProbability statistics:")
print(
    pd.Series(correctness_prob).describe()
)

============================================================
EVALUATING CORRECTNESS MODEL
============================================================

Accuracy: 0.7395 (73.95%)
ROC-AUC:  0.7984

Prediction distribution:
0    1010747
1    2115285
Name: count, dtype: int64

Probability statistics:
count    3.126032e+06
mean     6.425830e-01
std      2.371747e-01
min      1.348760e-01
25%      4.273116e-01
50%      6.724811e-01
75%      8.602138e-01
max      9.986857e-01
dtype: float64

In [41]:
# ============================================================
# CELL 32 — SAVE CORRECTNESS MODEL
# ============================================================

import joblib
from pathlib import Path

# Create models directory
MODELS_DIR = Path("../models")
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# Save model
correctness_model_path = MODELS_DIR / "learner_correctness_model.joblib"

joblib.dump(
    correctness_model,
    correctness_model_path
)

# Save feature names too
feature_names_path = MODELS_DIR / "learner_correctness_features.joblib"

joblib.dump(
    feature_cols,
    feature_names_path
)

print("=" * 60)
print("CORRECTNESS MODEL SAVED")
print("=" * 60)

print(f"Model:    {correctness_model_path.resolve()}")
print(f"Features: {feature_names_path.resolve()}")

print("\nFeatures saved:")
for i, feature in enumerate(feature_cols, 1):
    print(f"{i:2}. {feature}")

============================================================
CORRECTNESS MODEL SAVED
============================================================
Model:    C:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\models\learner_correctness_model.joblib
Features: C:\Users\Akshat\Desktop\Over_Here\Projects\Quintet\models\learner_correctness_features.joblib

Features saved:
 1. history_attempts
 2. history_correct
 3. history_accuracy
 4. history_questions
 5. history_subjects
 6. subject_attempts
 7. subject_correct
 8. subject_accuracy
 9. question_attempts
10. question_correct
11. question_accuracy